/**
 * Load static question content from JSON file.
 * In a real app, this would be replaced with dynamic content loading.
 * For now, returns a placeholder.
 */
export async function loadQuestionContent(subject: string, bank: string): Promise<any> {
	try {
		const response = await fetch(`/static/content/${subject}-${bank}.json`);
		if (!response.ok) {
			console.error(`Failed to load content: ${subject}-${bank}.json`);
			return null;
		}
		return await response.json();
	} catch (err) {
		console.error('Error loading question content:', err);
		return null;
	}
}

/**
 * Get list of available subjects and their content banks.
 * This is a placeholder; in Phase 8, this would be generated by build.py.
 */
export async function getAvailableContent(): Promise<Record<string, string[]>> {
	return {
		science: ['biology', 'chemistry', 'physics'],
		arts: ['english', 'history', 'geography'],
		commercial: ['accounting', 'economics', 'commerce']
	};
}
